trigger:
  batch: true
  branches:
    include:
      - main

pr:
  branches:
    include:
      - main

schedules:
  - cron: '0 0 * * 0'
    displayName: Weekly build
    branches:
      include:
        - main
    always: true

resources:
  repositories:
    - repository: ArchitectureRepo
      type: git
      name: Architecture/Architecture
      ref: refs/heads/main
    - repository: templates
      type: github
      name: AVEVA/AVEVA-Samples
      endpoint: AVEVA

variables:
  - name: analysisProject
    value: Auth-CC_Powershell

parameters:
  - name: pool
    default: DevOps-Managed-Ubt22-Mdp
  - name: containerDemands
    type: object
    default: ['Agent.OS -equals Windows_NT']

jobs:
  - job: Tests
    condition: ne(variables['Build.Reason'], 'Schedule')
    pool:
      name: ${{ parameters.pool }}
      demands: ${{ parameters.containerDemands }}
    steps:
      - template: '/miscellaneous/build_templates/appsettings.yml@templates'
        parameters:
          secrets: 'TenantId, ClientId, ClientSecret, Resource'

      - task: PowerShell@2
        inputs:
          targetType: 'filePath'
          filePath: $(System.DefaultWorkingDirectory)\GetToken.ps1
        displayName: 'Run tests'

  - job: Code_Analysis
    pool:
      name: ${{ parameters.pool }}
      demands: ${{ parameters.containerDemands }}
    steps:
      - powershell: Install-Module -Name PSScriptAnalyzer -Force
        displayName: Install code analyzer
        
      - powershell: Invoke-ScriptAnalyzer -EnableExit -Path GetToken.ps1
        failOnStderr: true
        displayName: Run analysis
        
  - template: '/miscellaneous/build_templates/code-analysis.yml@templates'
    parameters:
      skipPolaris: true
