trigger:
  batch: true
  branches:
    include:
      - main

pr:
  branches:
    include:
      - main

schedules:
  - cron: '0 0 * * 0'
    displayName: Weekly build
    branches:
      include:
        - main
    always: true

resources:
  repositories:
    - repository: OpsGuildAutomationRepo
      type: git
      name: Engineering/OpsGuild.Automation
      ref: refs/heads/main
    - repository: templates
      type: github
      name: osisoft/OSI-Samples
      endpoint: osisoft/OSI-Samples

variables:
  - template: '/miscellaneous/build_templates/variables.yml@templates'
  - name: analysisProject
    value: Auth-CC_Powershell

jobs:
  - job: Tests
    pool:
      name: 00-OSIManaged-Containers
      demands: Agent.OS -equals Windows_NT
    steps:
      - template: '/miscellaneous/build_templates/appsettings.yml@templates'
        parameters:
          secrets: 'TenantId, ClientId, ClientSecret, Resource'

      - task: PowerShell@2
        inputs:
          targetType: 'filePath'
          filePath: $(System.DefaultWorkingDirectory)\GetToken.ps1
        displayName: 'Run tests'

  - job: Code_Analysis
    pool:
      name: 00-OSIManaged-Containers
      demands: Agent.OS -equals Windows_NT
    steps:
      - powershell: Install-Module -Name PSScriptAnalyzer -Force
        displayName: Install code analyzer
        
      - powershell: Invoke-ScriptAnalyzer -Path GetToken.ps1
        displayName: Run analysis
        
  - template: '/miscellaneous/build_templates/code-analysis.yml@templates'
    parameters:
      skipPolaris: true
